=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/legespiel.config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://whatsoftwarecando.org"
	elementFormDefault="qualified" xmlns="http://whatsoftwarecando.org"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:appinfo>Legespiel-Solver</xs:appinfo>
		<xs:documentation>
			Schema for describing a scramble squares puzzle (or
			German: Legespiel). For more information visit
			https://github.com/keilhauer/Legespiel-Solver
		</xs:documentation>
	</xs:annotation>
	<xs:element name="legespielConfiguration"
		type="legespielConfigurationType" />
	<xs:complexType name="pictureType">
		<xs:attribute type="xs:byte" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="matchWithIds"
			use="required" />
	</xs:complexType>
	<xs:complexType name="picturesType">
		<xs:sequence>
			<xs:element type="pictureType" name="picture"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cardType">
		<xs:attribute type="xs:byte" name="north" use="required" />
		<xs:attribute type="xs:byte" name="west" use="required" />
		<xs:attribute type="xs:byte" name="east" use="required" />
		<xs:attribute type="xs:byte" name="south" use="required" />
	</xs:complexType>
	<xs:complexType name="cardsType">
		<xs:sequence>
			<xs:element type="cardType" name="card"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="legespielConfigurationType">
		<xs:sequence>
			<xs:element type="xs:string" name="name" minOccurs="0" />
			<xs:element type="xs:string" name="description" minOccurs="0" />
			<xs:element type="xs:byte" name="numberOfRows" />
			<xs:element type="xs:byte" name="numberOfColumns" />
			<xs:element type="picturesType" name="pictures" />
			<xs:element type="cardsType" name="cards" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/VerflixtFixUndFoxi.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Verflixt - Fix und Foxi</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2023/11/verflixt-fix-foxi.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Fix oben" matchWithIds="2" />
		<picture id="2" name="Fix unten" matchWithIds="1" />
		<picture id="3" name="Foxi oben" matchWithIds="4" />
		<picture id="4" name="Foxi unten" matchWithIds="3" />
		<picture id="5" name="Lupo oben" matchWithIds="6" />
		<picture id="6" name="Lupo unten" matchWithIds="5" />
		<picture id="7" name="Lupinchen oben" matchWithIds="8" />
		<picture id="8" name="Lupinchen unten" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="3" east="8" south="5" />
		<card north="8" west="7" east="6" south="3" />
		<card north="8" west="5" east="2" south="3" />
		<card north="6" west="7" east="2" south="3" />
		<card north="4" west="1" east="8" south="5" />
		<card north="4" west="1" east="2" south="5" />
		<card north="4" west="5" east="8" south="3" />
		<card north="6" west="7" east="2" south="5" />
		<card north="6" west="1" east="8" south="3" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/HotAirBalloonsScrambleSquares.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Hot Air Balloons Scramble Squares</name>
	<description>See https://www.worthpoint.com/worthopedia/scramble-squares-puzzles-lot-hot-air-1849556943</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="VIOLET YELLOW LEFT" matchWithIds="6" />
		<picture id="2" name="RAINBOW SQUARES UP" matchWithIds="8" />
		<picture id="3" name="ZIGZAG UP" matchWithIds="5" />
		<picture id="4" name="EAGLE LEFT" matchWithIds="7" />
		<picture id="5" name="ZIGZAG LOW" matchWithIds="3" />
		<picture id="6" name="VIOLET YELLOW RIGHT" matchWithIds="1" />
		<picture id="7" name="EAGLE RIGHT" matchWithIds="4" />
		<picture id="8" name="RAINBOW SQUARES LOW" matchWithIds="2" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="4" west="5" east="1" south="2" />
		<card north="3" west="6" east="2" south="4" />
		<card north="7" west="8" east="5" south="1" />
		<card north="8" west="3" east="6" south="2" />
		<card north="7" west="6" east="1" south="3" />
		<card north="6" west="3" east="8" south="7" />
		<card north="8" west="5" east="4" south="7" />
		<card north="3" west="6" east="4" south="8" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/WernerKnobelei.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Werner-Knobelei</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2023/10/werner-knobelei.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Werner oben" matchWithIds="2" />
		<picture id="2" name="Werner unten" matchWithIds="1" />
		<picture id="3" name="MC Klappstuhl oben" matchWithIds="4" />
		<picture id="4" name="MC Klappstuhl unten" matchWithIds="3" />
		<picture id="5" name="Andi oben" matchWithIds="6" />
		<picture id="6" name="Andi unten" matchWithIds="5" />
		<picture id="7" name="Kalli oben" matchWithIds="8" />
		<picture id="8" name="Kalli unten" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="1" west="6" east="4" south="7" />
		<card north="5" west="3" east="2" south="8" />
		<card north="1" west="1" east="6" south="7" />
		<card north="8" west="3" east="2" south="5" />
		<card north="7" west="1" east="4" south="6" />
		<card north="8" west="3" east="5" south="2" />
		<card north="6" west="4" east="1" south="7" />
		<card north="5" west="2" east="8" south="3" />
		<card north="2" west="3" east="5" south="8" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/ChildsPuzzleThree.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Child&apos;s Puzzle Three / Kinderpuzzle Nr. 3</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2023/04/childs-puzzle-three-kinderpuzzle-nr-3.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Anker rechts" matchWithIds="2" />
		<picture id="2" name="Anker links" matchWithIds="1" />
		<picture id="3" name="Eule rechts" matchWithIds="4" />
		<picture id="4" name="Eule links" matchWithIds="3" />
		<picture id="5" name="Fisch rechts" matchWithIds="6" />
		<picture id="6" name="Fisch links" matchWithIds="5" />
		<picture id="7" name="Mensch rechts" matchWithIds="8" />
		<picture id="8" name="Mensch links" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="1" east="6" south="8" />
		<card north="6" west="5" east="4" south="3" />
		<card north="8" west="3" east="1" south="5" />
		<card north="7" west="5" east="6" south="4" />
		<card north="4" west="5" east="6" south="7" />
		<card north="6" west="5" east="3" south="1" />
		<card north="3" west="7" east="4" south="2" />
		<card north="8" west="3" east="1" south="4" />
		<card north="5" west="2" east="4" south="7" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/LemonAndHerbs.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Lemon and Herbs</name>
	<description>MDF Coasters - The solution could not be verified, because the image on Amazon seems to be incorrect: https://www.amazon.com/Piece-Scramble-Square-Puzzle-Housewarming/dp/B0CCMLSQLS?th=1</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Olive 1" matchWithIds="8" />
		<picture id="2" name="Lemon Dark" matchWithIds="7" />
		<picture id="3" name="Mint Stem" matchWithIds="6" />
		<picture id="4" name="Rosemary Stem" matchWithIds="5" />
		<picture id="5" name="Rosemary Top" matchWithIds="4" />
		<picture id="6" name="Mint Top" matchWithIds="3" />
		<picture id="7" name="Lemon Light" matchWithIds="2" />
		<picture id="8" name="Olive 2" matchWithIds="1" />
	</pictures>
	<cards>
		<card north="8" west="6" east="2" south="4" />
		<card north="6" west="1" east="5" south="2" />
		<card north="5" west="8" east="3" south="2" />
		<card north="3" west="1" east="8" south="5" />
		<card north="8" west="7" east="3" south="1" />
		<card north="1" west="8" east="3" south="5" />
		<card north="5" west="7" east="2" south="3" />
		<card north="2" west="5" east="4" south="6" />
		<card north="8" west="7" east="3" south="4" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/TheCrazyKittyGame.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>The Crazy Kitty Game</name>
	<description>Crazy Puzzle Games - From a large series of 3x3 puzzles released in the 1980s and 1990s by Price Stern Sloan. More info can be found here: https://www.geekyhobbies.com/the-crazy-game-puzzles-puzzled/</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Orange Head" matchWithIds="2" />
		<picture id="2" name="Orange Feet" matchWithIds="1" />
		<picture id="3" name="Blue Head" matchWithIds="4" />
		<picture id="4" name="Blue Feet" matchWithIds="3" />
		<picture id="5" name="Pink Head" matchWithIds="6" />
		<picture id="6" name="Pink Feet" matchWithIds="5" />
		<picture id="7" name="Green Head" matchWithIds="8" />
		<picture id="8" name="Green Feet" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="3" east="6" south="7" />
		<card north="6" west="7" east="4" south="1" />
		<card north="7" west="3" east="6" south="2" />
		<card north="6" west="3" east="8" south="1" />
		<card north="2" west="7" east="8" south="5" />
		<card north="8" west="3" east="2" south="5" />
		<card north="2" west="7" east="4" south="5" />
		<card north="6" west="3" east="4" south="1" />
		<card north="6" west="3" east="8" south="1" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/RetrieverScrambleSquares.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Retriever Scramble Squares</name>
	<description>See https://kalmas.net/blog/2014-01-01_scramble-squares/</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="PANTING FRONT" matchWithIds="7" />
		<picture id="2" name="BLACK FRONT" matchWithIds="6" />
		<picture id="3" name="BROWN BACK" matchWithIds="5" />
		<picture id="4" name="WITH STICK FRONT" matchWithIds="8" />
		<picture id="5" name="BROWN FRONT" matchWithIds="3" />
		<picture id="6" name="BLACK BACK" matchWithIds="2" />
		<picture id="7" name="PANGTIN BACK" matchWithIds="1" />
		<picture id="8" name="WITH STICK BACK" matchWithIds="4" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="4" west="5" east="1" south="6" />
		<card north="5" west="7" east="4" south="2" />
		<card north="8" west="5" east="1" south="2" />
		<card north="2" west="7" east="4" south="5" />
		<card north="6" west="8" east="7" south="3" />
		<card north="6" west="4" east="7" south="5" />
		<card north="3" west="1" east="8" south="2" />
		<card north="5" west="4" east="2" south="1" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/SpaceWeb.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Space Web</name>
	<description>Space Web Arrangement Puzzle, Gordon Bros. 1979
	https://welt-der-geduldspiele.blogspot.com/2022/10/space-web.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="1" matchWithIds="4" />
		<picture id="2" name="2" matchWithIds="3" />
		<picture id="3" name="3" matchWithIds="2" />
		<picture id="4" name="4" matchWithIds="1" />
	</pictures>
	<cards>
		<card north="4" west="2" east="2" south="4" />
		<card north="1" west="3" east="3" south="1" />
		<card north="3" west="2" east="2" south="3" />
		<card north="1" west="1" east="3" south="3" />
		<card north="4" west="2" east="4" south="2" />
		<card north="2" west="1" east="3" south="4" />
		<card north="2" west="1" east="3" south="4" />
		<card north="3" west="2" east="2" south="3" />
		<card north="4" west="1" east="3" south="2" />
	</cards>
</legespielConfiguration>
