=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/legespiel.config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://whatsoftwarecando.org"
	elementFormDefault="qualified" xmlns="http://whatsoftwarecando.org"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:appinfo>Legespiel-Solver</xs:appinfo>
		<xs:documentation>
			Schema for describing a scramble squares puzzle (or
			German: Legespiel). For more information visit
			https://github.com/keilhauer/Legespiel-Solver
		</xs:documentation>
	</xs:annotation>
	<xs:element name="legespielConfiguration"
		type="legespielConfigurationType" />
	<xs:complexType name="pictureType">
		<xs:attribute type="xs:byte" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="matchWithIds"
			use="required" />
	</xs:complexType>
	<xs:complexType name="picturesType">
		<xs:sequence>
			<xs:element type="pictureType" name="picture"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cardType">
		<xs:attribute type="xs:byte" name="north" use="required" />
		<xs:attribute type="xs:byte" name="west" use="required" />
		<xs:attribute type="xs:byte" name="east" use="required" />
		<xs:attribute type="xs:byte" name="south" use="required" />
	</xs:complexType>
	<xs:complexType name="cardsType">
		<xs:sequence>
			<xs:element type="cardType" name="card"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="legespielConfigurationType">
		<xs:sequence>
			<xs:element type="xs:string" name="name" minOccurs="0" />
			<xs:element type="xs:string" name="description" minOccurs="0" />
			<xs:element type="xs:byte" name="numberOfRows" />
			<xs:element type="xs:byte" name="numberOfColumns" />
			<xs:element type="picturesType" name="pictures" />
			<xs:element type="cardsType" name="cards" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/RSpiel.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>r-Spiel</name>
	<description>FÃ¶rderverein Gutenbergmuseum, Mainz</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="r1 oben" matchWithIds="2" />
		<picture id="2" name="r1 unten" matchWithIds="1" />
		<picture id="3" name="r2 oben" matchWithIds="4" />
		<picture id="4" name="r2 unten" matchWithIds="3" />
		<picture id="5" name="r3 oben" matchWithIds="6" />
		<picture id="6" name="r3 unten" matchWithIds="5" />
		<picture id="7" name="r4 oben" matchWithIds="8" />
		<picture id="8" name="r4 unten" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="4" west="1" east="8" south="5" />
		<card north="4" west="7" east="6" south="1" />
		<card north="8" west="5" east="4" south="1" />
		<card north="6" west="3" east="8" south="1" />
		<card north="2" west="7" east="4" south="5" />
		<card north="6" west="3" east="2" south="1" />
		<card north="2" west="3" east="8" south="5" />
		<card north="6" west="7" east="4" south="5" />
		<card north="2" west="3" east="8" south="1" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/TheCrazyFrogGame.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>The Crazy Frog Game</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2024/05/the-crazy-frog-game.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="rot Kopf" matchWithIds="2" />
		<picture id="2" name="rot Körper" matchWithIds="1" />
		<picture id="3" name="grün Kopf" matchWithIds="4" />
		<picture id="4" name="grün Körper" matchWithIds="3" />
		<picture id="5" name="blau Kopf" matchWithIds="6" />
		<picture id="6" name="blau Körper" matchWithIds="5" />
		<picture id="7" name="türkis Kopf" matchWithIds="8" />
		<picture id="8" name="türkis Körper" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="8" east="3" south="5" />
		<card north="8" west="2" east="3" south="7" />
		<card north="8" west="4" east="5" south="1" />
		<card north="6" west="2" east="3" south="5" />
		<card north="8" west="4" east="3" south="1" />
		<card north="2" west="4" east="5" south="7" />
		<card north="6" west="2" east="5" south="3" />
		<card north="2" west="6" east="5" south="7" />
		<card north="8" west="6" east="3" south="1" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/HarryPotter.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Harry Potter</name>
	<description>Head2Toe - www.advancegames.net 2020</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Hufflepuff up" matchWithIds="2" />
		<picture id="2" name="Hufflepuff down" matchWithIds="1" />
		<picture id="3" name="Gryffindor up" matchWithIds="4" />
		<picture id="4" name="Gryffindor down" matchWithIds="3" />
		<picture id="5" name="Slytherin up" matchWithIds="6" />
		<picture id="6" name="Slytherin down" matchWithIds="5" />
		<picture id="7" name="Ravenclaw up" matchWithIds="8" />
		<picture id="8" name="Ravenclaw down" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="3" west="5" east="4" south="2" />
		<card north="8" west="1" east="3" south="1" />
		<card north="8" west="6" east="6" south="7" />
		<card north="2" west="4" east="7" south="1" />
		<card north="2" west="3" east="3" south="6" />
		<card north="5" west="8" east="1" south="6" />
		<card north="5" west="8" east="8" south="4" />
		<card north="1" west="4" east="7" south="6" />
		<card north="3" west="2" east="5" south="7" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/UliSteinNochVerzwickter.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Uli Stein: Noch verzwickter</name>
	<description>See http://www.lenz-online.de/aboutme/history/ulstein0.htm for more information.</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="PENGUIN RIGHT" matchWithIds="6" />
		<picture id="2" name="MOUSE RIGHT" matchWithIds="7" />
		<picture id="3" name="CAT LEFT" matchWithIds="5" />
		<picture id="4" name="PIG LEFT" matchWithIds="8" />
		<picture id="5" name="CAT RIGHT" matchWithIds="3" />
		<picture id="6" name="PENGUIN LEFT" matchWithIds="1" />
		<picture id="7" name="MOUSE LEFT" matchWithIds="2" />
		<picture id="8" name="PIG RIGHT" matchWithIds="4" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="4" west="5" east="2" south="6" />
		<card north="5" west="7" east="6" south="8" />
		<card north="8" west="6" east="2" south="3" />
		<card north="1" west="7" east="3" south="8" />
		<card north="4" west="5" east="7" south="1" />
		<card north="5" west="4" east="6" south="2" />
		<card north="4" west="1" east="7" south="5" />
		<card north="6" west="2" east="8" south="3" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/KnifflidiffelsVersion1.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Diddl Knifflidiffels (Version 1)</name>
	<description>This is version 1 according to
		https://whatsoftwarecando.org/list-of-scramble-squares-puzzles-with-solutions/
		.
	</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="BALLOONS" matchWithIds="1" />
		<picture id="2" name="BEAR" matchWithIds="2" />
		<picture id="3" name="GIRL" matchWithIds="3" />
		<picture id="4" name="BOY" matchWithIds="4" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="4" west="3" east="2" south="1" />
		<card north="1" west="2" east="3" south="4" />
		<card north="1" west="3" east="2" south="4" />
		<card north="4" west="2" east="3" south="1" />
		<card north="3" west="1" east="4" south="2" />
		<card north="3" west="2" east="1" south="4" />
		<card north="3" west="1" east="2" south="4" />
		<card north="1" west="3" east="4" south="2" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/UliSteinTierischVerzwickt.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Uli Stein - Tierisch VERZWICKT</name>
	<description>Uli Stein Legespiel von 1993</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Katze oben" matchWithIds="2" />
		<picture id="2" name="Katze unten" matchWithIds="1" />
		<picture id="3" name="Maus oben" matchWithIds="4" />
		<picture id="4" name="Maus unten" matchWithIds="3" />
		<picture id="5" name="Pinguin oben" matchWithIds="6" />
		<picture id="6" name="Pinguin unten" matchWithIds="5" />
		<picture id="7" name="Schwein oben" matchWithIds="8" />
		<picture id="8" name="Schwein unten" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="4" west="5" east="1" south="8" />
		<card north="2" west="6" east="7" south="3" />
		<card north="2" west="3" east="6" south="7" />
		<card north="4" west="1" east="8" south="5" />
		<card north="8" west="3" east="5" south="2" />
		<card north="6" west="4" east="8" south="1" />
		<card north="4" west="7" east="2" south="5" />
		<card north="1" west="8" east="3" south="7" />
		<card north="2" west="7" east="3" south="6" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/DieKatzenKnobelei.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
    xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Die Katzen-Knobelei</name>
	<description>See https://www.ebay-kleinanzeigen.de/s-anzeige/die-katzen-knobelei-spiel-alt-selten-raritaet-sammler-ass/1594696783-240-8325
	---
	This content submitted by a user of Legespiel-Solver online. Thank you! &lt;3</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Rot Kopf" matchWithIds="6" />
		<picture id="2" name="Lila Kopf" matchWithIds="3" />
		<picture id="3" name="Lila Schwanz" matchWithIds="2" />
		<picture id="4" name="Blau Schwanz" matchWithIds="7" />
		<picture id="5" name="Orange Kopf" matchWithIds="8" />
		<picture id="6" name="Rot Schwanz" matchWithIds="1" />
		<picture id="7" name="Blau Kopf" matchWithIds="4" />
		<picture id="8" name="Orange Schwanz" matchWithIds="5" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="5" west="4" east="2" south="6" />
		<card north="7" west="5" east="3" south="6" />
		<card north="5" west="2" east="4" south="6" />
		<card north="7" west="5" east="8" south="6" />
		<card north="1" west="5" east="3" south="4" />
		<card north="1" west="2" east="8" south="4" />
		<card north="2" west="4" east="1" south="8" />
		<card north="7" west="2" east="6" south="8" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/LeapinLizards.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Leapin&apos; Lizards (Lagoon)</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2024/11/leapin-lizards-eidechsen.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Grün Kopf" matchWithIds="2" />
		<picture id="2" name="Grün Schwanz" matchWithIds="1" />
		<picture id="3" name="Blau Kopf" matchWithIds="4" />
		<picture id="4" name="Blau Schwanz" matchWithIds="3" />
		<picture id="5" name="Schwarz Kopf" matchWithIds="6" />
		<picture id="6" name="Schwarz Schwanz" matchWithIds="5" />
		<picture id="7" name="Bunt Kopf" matchWithIds="8" />
		<picture id="8" name="Bunt Schwanz" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="5" west="1" east="2" south="4" />
		<card north="5" west="1" east="7" south="2" />
		<card north="8" west="8" east="4" south="1" />
		<card north="3" west="6" east="4" south="8" />
		<card north="1" west="3" east="5" south="6" />
		<card north="2" west="6" east="3" south="2" />
		<card north="7" west="3" east="7" south="6" />
		<card north="5" west="7" east="8" south="4" />
		<card north="1" west="7" east="3" south="6" />
	</cards>
</legespielConfiguration>
