=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/legespiel.config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema targetNamespace="http://whatsoftwarecando.org"
	elementFormDefault="qualified" xmlns="http://whatsoftwarecando.org"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:appinfo>Legespiel-Solver</xs:appinfo>
		<xs:documentation>
			Schema for describing a scramble squares puzzle (or
			German: Legespiel). For more information visit
			https://github.com/keilhauer/Legespiel-Solver
		</xs:documentation>
	</xs:annotation>
	<xs:element name="legespielConfiguration"
		type="legespielConfigurationType" />
	<xs:complexType name="pictureType">
		<xs:attribute type="xs:byte" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:string" name="matchWithIds"
			use="required" />
	</xs:complexType>
	<xs:complexType name="picturesType">
		<xs:sequence>
			<xs:element type="pictureType" name="picture"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cardType">
		<xs:attribute type="xs:byte" name="north" use="required" />
		<xs:attribute type="xs:byte" name="west" use="required" />
		<xs:attribute type="xs:byte" name="east" use="required" />
		<xs:attribute type="xs:byte" name="south" use="required" />
	</xs:complexType>
	<xs:complexType name="cardsType">
		<xs:sequence>
			<xs:element type="cardType" name="card"
				maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="legespielConfigurationType">
		<xs:sequence>
			<xs:element type="xs:string" name="name" minOccurs="0" />
			<xs:element type="xs:string" name="description" minOccurs="0" />
			<xs:element type="xs:byte" name="numberOfRows" />
			<xs:element type="xs:byte" name="numberOfColumns" />
			<xs:element type="picturesType" name="pictures" />
			<xs:element type="cardsType" name="cards" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/NorisPassts.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>NORIS Passt&apos;s?</name>
	<description>https://www.amazon.de/Noris-Spiele-606094228-Passts-Kinderspiel/dp/B01MSAOQ6X</description>
	---
	This content was submitted by a user of Legespiel-Solver online. Thank you! &lt;3
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Apple upper" matchWithIds="2" />
		<picture id="2" name="Apple lower" matchWithIds="1" />
		<picture id="3" name="Cat upper" matchWithIds="4" />
		<picture id="4" name="Cat lower" matchWithIds="3" />
		<picture id="5" name="Caterpillar front" matchWithIds="6" />
		<picture id="6" name="Caterpillar rear" matchWithIds="5" />
		<picture id="7" name="Mouse front" matchWithIds="8" />
		<picture id="8" name="Mouse rear" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="7" east="8" south="5" />
		<card north="2" west="8" east="5" south="3" />
		<card north="8" west="4" east="5" south="1" />
		<card north="2" west="5" east="4" south="3" />
		<card north="2" west="6" east="3" south="7" />
		<card north="1" west="3" east="6" south="8" />
		<card north="4" west="7" east="2" south="3" />
		<card north="8" west="6" east="5" south="1" />
		<card north="3" west="5" east="2" south="4" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/JapanischesKartenrätsel-einfach.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Japanisches Kartenrätsel - Sechsecke (einfache Variante)</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2022/11/kartenratsel-sechsecke-einfache-variante.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="rot" matchWithIds="1" />
		<picture id="2" name="gelb" matchWithIds="2" />
		<picture id="3" name="grün" matchWithIds="3" />
		<picture id="4" name="blau" matchWithIds="4" />
	</pictures>
	<cards>
		<card north="3" west="2" east="1" south="3" />
		<card north="4" west="1" east="3" south="2" />
		<card north="4" west="3" east="1" south="2" />
		<card north="3" west="4" east="4" south="2" />
		<card north="2" west="4" east="3" south="1" />
		<card north="2" west="3" east="4" south="1" />
		<card north="2" west="3" east="4" south="1" />
		<card north="1" west="4" east="3" south="2" />
		<card north="1" west="2" east="3" south="4" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/DieBaerenKnobelei.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Die Bärenknobelei</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2023/03/die-barenknobelei.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Eisbär Kopf" matchWithIds="2" />
		<picture id="2" name="Eisbär Hinterteil" matchWithIds="1" />
		<picture id="3" name="Grizzly Kopf" matchWithIds="4" />
		<picture id="4" name="Grizzly Hinterteil" matchWithIds="3" />
		<picture id="5" name="Braunbär Kopf" matchWithIds="6" />
		<picture id="6" name="Braunbär Hinterteil" matchWithIds="5" />
		<picture id="7" name="Panda Kopf" matchWithIds="8" />
		<picture id="8" name="Panda Hinterteil" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="3" west="7" east="1" south="5" />
		<card north="6" west="2" east="7" south="4" />
		<card north="3" west="8" east="5" south="1" />
		<card north="6" west="2" east="7" south="4" />
		<card north="3" west="8" east="6" south="1" />
		<card north="2" west="5" east="3" south="8" />
		<card north="5" west="4" east="7" south="2" />
		<card north="2" west="4" east="6" south="8" />
		<card north="7" west="5" east="1" south="4" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/DasVerflixteFelixPuzzle.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Das verflixte Felix Puzzle - Spiel</name>
	<description>Legespiel aus dem Jahr 1998
	Passend zu den Felix BÃ¼chern von Annette Langen
	Herausgegeben von &quot;Die Spielburg&quot; im Coppenrath Verlag</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Astronautenkopf" matchWithIds="2" />
		<picture id="2" name="Astronautenpo" matchWithIds="1" />
		<picture id="3" name="Wikingerkopf" matchWithIds="4" />
		<picture id="4" name="Wikingerpo" matchWithIds="3" />
		<picture id="5" name="Hasenkopf" matchWithIds="6" />
		<picture id="6" name="Hasenpo" matchWithIds="5" />
		<picture id="7" name="Schwimmerkopf" matchWithIds="8" />
		<picture id="8" name="Schwimmerpo" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="8" west="4" east="7" south="5" />
		<card north="2" west="8" east="5" south="3" />
		<card north="2" west="7" east="4" south="5" />
		<card north="4" west="7" east="8" south="5" />
		<card north="1" west="5" east="4" south="2" />
		<card north="4" west="8" east="7" south="1" />
		<card north="3" west="7" east="6" south="2" />
		<card north="3" west="5" east="6" south="2" />
		<card north="1" west="7" east="6" south="4" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/UliSteinNochVerwzickterGehtNicht.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Uli Stein: Noch verwzickter geht nicht!</name>
	<description>See http://www.gerdkoch.de/nochverwzickter/index.html for more information.</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="GLASS RIGHT" matchWithIds="6" />
		<picture id="2" name="REACHING RIGHT" matchWithIds="7" />
		<picture id="3" name="FOOTBALL LEFT" matchWithIds="5" />
		<picture id="4" name="TEA LEFT" matchWithIds="8" />
		<picture id="5" name="FOOTBALL RIGHT" matchWithIds="3" />
		<picture id="6" name="GLASS LEFT" matchWithIds="1" />
		<picture id="7" name="REACHING LEFT" matchWithIds="2" />
		<picture id="8" name="TEA RIGHT" matchWithIds="4" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="4" west="5" east="2" south="6" />
		<card north="5" west="7" east="6" south="8" />
		<card north="8" west="6" east="2" south="3" />
		<card north="1" west="7" east="3" south="8" />
		<card north="4" west="5" east="7" south="1" />
		<card north="5" west="4" east="6" south="2" />
		<card north="4" west="1" east="7" south="5" />
		<card north="6" west="2" east="8" south="3" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/DuckulaDerVerflixte.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Duckula der Verflixte</name>
	<description>Quasthoff version 2</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="Turned around upper" matchWithIds="2" />
		<picture id="2" name="Turned around lower" matchWithIds="1" />
		<picture id="3" name="Scared upper" matchWithIds="4" />
		<picture id="4" name="Scared lower" matchWithIds="3" />
		<picture id="5" name="Eyes covered upper" matchWithIds="6" />
		<picture id="6" name="Eyes covered lower" matchWithIds="5" />
		<picture id="7" name="Happy upper" matchWithIds="8" />
		<picture id="8" name="Happy lower" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="2" west="4" east="3" south="7" />
		<card north="2" west="4" east="5" south="7" />
		<card north="4" west="6" east="1" south="7" />
		<card north="8" west="6" east="5" south="1" />
		<card north="8" west="6" east="3" south="1" />
		<card north="8" west="4" east="1" south="5" />
		<card north="2" west="4" east="5" south="7" />
		<card north="2" west="6" east="3" south="7" />
		<card north="6" west="4" east="7" south="1" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/CatsScrambleSquares.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>Cats Scramble Squares</name>
	<description>see https://www.flickr.com/photos/greatshotsbyjf/6649252505</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="BROWN LOW" matchWithIds="7" />
		<picture id="2" name="WHITE GRAY LOW" matchWithIds="8" />
		<picture id="3" name="BLACK LEFT" matchWithIds="6" />
		<picture id="4" name="WHITE RED LOW" matchWithIds="5" />
		<picture id="5" name="WHITE RED UP" matchWithIds="4" />
		<picture id="6" name="BLACK RIGHT" matchWithIds="3" />
		<picture id="7" name="BROWN UP" matchWithIds="1" />
		<picture id="8" name="WHITE GRAY UP" matchWithIds="2" />
	</pictures>
	<cards>
		<card north="1" west="2" east="3" south="4" />
		<card north="5" west="6" east="2" south="7" />
		<card north="6" west="8" east="5" south="6" />
		<card north="5" west="8" east="6" south="7" />
		<card north="1" west="3" east="8" south="4" />
		<card north="3" west="2" east="7" south="5" />
		<card north="1" west="5" east="2" south="3" />
		<card north="5" west="8" east="7" south="2" />
		<card north="4" west="1" east="1" south="3" />
	</cards>
</legespielConfiguration>

=== keilhauer/Legespiel-Solver/src/main/resources/org/whatsoftwarecando/legespiel/xml/configs/WährungsTüftelspielVorderseite.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<legespielConfiguration
	xmlns="http://whatsoftwarecando.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://whatsoftwarecando.org/legespiel.config.xsd http://whatsoftwarecando.org">
	<name>W채hrungs-T체ftelspiel (Vorderseite)</name>
	<description>https://welt-der-geduldspiele.blogspot.com/2024/04/wahrungs-tuftelspiel-vorderseite.html</description>
	<numberOfRows>3</numberOfRows>
	<numberOfColumns>3</numberOfColumns>
	<pictures>
		<picture id="1" name="blau links" matchWithIds="2" />
		<picture id="2" name="blau rechts" matchWithIds="1" />
		<picture id="3" name="braun links" matchWithIds="4" />
		<picture id="4" name="braun rechts" matchWithIds="3" />
		<picture id="5" name="dollar links" matchWithIds="6" />
		<picture id="6" name="dollar rechts" matchWithIds="5" />
		<picture id="7" name="gr체n links" matchWithIds="8" />
		<picture id="8" name="gr체n rechts" matchWithIds="7" />
	</pictures>
	<cards>
		<card north="7" west="2" east="3" south="6" />
		<card north="6" west="4" east="7" south="1" />
		<card north="6" west="8" east="1" south="3" />
		<card north="3" west="4" east="3" south="2" />
		<card north="2" west="4" east="5" south="7" />
		<card north="4" west="6" east="1" south="7" />
		<card north="1" west="4" east="5" south="8" />
		<card north="8" west="6" east="5" south="1" />
		<card north="8" west="6" east="3" south="1" />
	</cards>
</legespielConfiguration>
